### ISSUE TITLE
Trouble with special characters

### ISSUE THREAD

**Issue by RunarAnd** [profesorfalken/jPowerShell#16]
When one is trying to pass special characters it fails
To recreate:

`public class Main {
    public static void main(String[] args){
        //Execute a command in PowerShell session
        PowerShellResponse response = PowerShell.executeSingleCommand("$var1 = \"æøøå\"; $var1 | Out-File text.txt");

        //Print results
        System.out.println(response.getCommandOutput());

    }
}`

The content of the text.txt file is then ├ª├©├©├Ñ and it should be "æøøå"

**Comment by profesorfalken** [comment]
Hello, 

It is weird because normally it will use the default encoding of your system JVM.

I have build a snapshot version that contains a modification in order to force UTF-8. 

Could you check if it works?
https://oss.sonatype.org/content/repositories/snapshots/com/profesorfalken/jPowerShell/1.7-SNAPSHOT/jPowerShell-1.7-20170423.164412-1.jar

Best regards

**Comment by Harinus** [comment]
Hi,

the issue is that the Powershell instance is not using the JVM default Encoding.
See my Pull Request. 

Best Regards,
Harinus
